### ISSUE TITLE
Increase the Size of logo in navbar

### ISSUE THREAD

**Issue by KhyathiKancharla** [chaitu43/FarmSwecha#7]
Hi, I would like to increase the size of logo in navbar as the text size dominates the logo in the navbar section.
please assign this issue .

Thank you

![image](https://github.com/chaitu43/FarmSwecha/assets/110332342/4ac41a5e-ff79-4fce-bcf0-62c39688c30f)

**Comment by SALMANKHANPM** [comment]
Fixed
