### ISSUE TITLE
inefficient naming convention

### ISSUE THREAD

**Issue by jitendhar27** [chaitu43/FarmSwecha#8]
the names of market price and soil testing page are not following naming convention. !
![Screenshot 2023-10-10 183655](https://github.com/chaitu43/FarmSwecha/assets/123219751/c3a21efb-683d-4688-b3b5-1c9b10104abf)

I would like to enhance the Naming Conventions as contribution as part of the Hacktoberfest.

**Comment by VanshBhardwaj24** [comment]
@jitendhar27 please assign this issue

**Comment by SALMANKHANPM** [comment]
Fixed
