### ISSUE TITLE
Bug: Menu icon of navbar is not visibile

### ISSUE THREAD

**Issue by Mayank-Sharma17** [chaitu43/FarmSwecha#9]
In mobile view the menu icon is not visible, and the logo size is too small can we increase the size of the logo ?

![Screenshot 2023-10-19 135837](https://github.com/chaitu43/FarmSwecha/assets/113251342/f0ebd15a-f7f4-4bc5-8e4b-cc14efcf8303)

**Comment by SALMANKHANPM** [comment]
Fixed
